version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  backend:
    container_name: Text2Map-API
    build: ./backend
    networks:
      - app-network
    ports:
      - "8000:8000"
    environment:
      - UVICORN_WORKERS=1
      - OPENAI_API_KEY=Put your openai api key here

  frontend:
    container_name: Text2Map-Website
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "80:3000"