/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/brWdjky99ni
 */
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { CloseIcon, PaintbrushIcon } from "../ui/icons";
import { Textarea } from "@/components/ui/textarea"
import React, {useState} from "react";

export function EditMarker({ onClose, onTitleChange, title }: { 
  onClose: () => void;
  onTitleChange: (newTitle: string) => void;
  title: string;
 }) {

  const [inputTitle, setInputTitle] = useState(title);

  const handleUpdate = () => {
    onTitleChange(inputTitle);
    onClose();
  }

  return (
    <div className="fixed inset-0 bg-gray-500 bg-opacity-75 flex items-center justify-center p-4">
      <div className="bg-white rounded-lg max-w-2xl w-full p-6 space-y-4 relative">
        <button className="absolute top-4 right-4">
          <CloseIcon className="h-6 w-6" onClick={onClose}/>
        </button>
        <h2 className="text-xl font-semibold">Edit location</h2>
        <div className="flex flex-col space-y-3">
          <div className="flex items-center space-x-3">
            <Input placeholder="Location name / Address / Lat. - Long." value={inputTitle} onChange={(e) => setInputTitle(e.target.value)}/>
            <Button className="flex-shrink-0" variant="outline">
              <PaintbrushIcon className="h-5 w-5" />
            </Button>
          </div>
          <Textarea placeholder="Add details and information about this location..." />
        </div>
        <Button className="w-full" onClick={handleUpdate}>Update</Button>
      </div>
    </div>
  )
}
